shsj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from volunteer import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shsj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^djangoadmin/', include(admin.site.urls)),
    url(r'^$', views.homepage),
    url(r'^signup/$', views.signup),
    url(r'^login/$',views.login),
    url(r'^logout/$',views.logout),
    url(r'^submitreport/$',views.submit_report),
    url(r'^reportlist/$',views.report_list),
    url(r'^reportlist/edit/$',views.report_edit),
    url(r'^reportlist/detail/$',views.report_detail),
    url(r'^auditinglist/$',views.auditing_list),
    url(r'^reportlist/auditing/$',views.report_auditing),
    url(r'^querry/$',views.querry),
    url(r'^setpasswd/$',views.setpasswd),
)

volunteer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MyUser(models.Model):
	name = models.CharField(max_length = 32)
	num = models.CharField(max_length = 11)
	classnum = models.CharField(max_length = 8)
	permission = models.IntegerField()
	headImg = models.URLField()

	user = models.OneToOneField(User)

	def __unicode__(self):
		return self.name

class Report(models.Model):
	name = models.CharField(max_length = 128)
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	submit_time = models.DateTimeField(auto_now=True)
	apply_time = models.FloatField()
	apply_score = models.FloatField()
	address = models.CharField(max_length = 128)
	info = models.TextField(max_length = 20480)
	status = models.IntegerField()
	report_type = models.IntegerField()
	author_type = models.IntegerField()
	info_type = models.IntegerField()
	img1 = models.URLField(null=True)
	img2 = models.URLField(null=True)

	author = models.ForeignKey(MyUser)
	checker = models.CharField(max_length = 32,null=True)

	def __unicode__(self):
		return self.author.name + '<<' + self.name + '>>'

volunteer/views.py
from django.shortcuts import render, render_to_response
from django.template import Context, RequestContext
from models import *
import re
import datetime
from markdown import markdown
from random import randint
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.models import User

from sae.storage import Bucket, Client
from sae.ext.storage import monkey
monkey.patch_all()

# Create your views here.

def get_headimg(number):
	if number:
		pic = 'http://xscj.hit.edu.cn/hitjwgl/XS/XSZP/ZP'+number[:3]+'/'+number+'.jpg'
		return pic
	else:
		return ''

def num_need_check():
	check_lst = Report.objects.filter(status = 1)
	return len(check_lst)

def homepage(req):
	username = req.session.get('username','')
	content = {'active_menu':'homepage','num_need_check':num_need_check()}
	if username != '':
		user = MyUser.objects.get(user__username = username)
		content['user'] = user
	else:
		content['user'] = ''
	return render_to_response('index.html',content)

def signup(req):
	if req.session.get('username',''):
		return HttpResponseRedirect('/')
	status = ''
	if req.POST:
		post = req.POST
		passwd = post.get('passwd','')
		repasswd = post.get('repasswd','')
		if passwd != repasswd:
			status = 're_err'
		elif len(post.get('classnum','')) != 8:
			status = 'classnum_err'
		else:
			if User.objects.filter(username = post.get('username','')):
				status = 'user_exist'
			elif MyUser.objects.filter(num = post.get('num','')):
				status = 'num_exist'
			else:
				newuser = User.objects.create_user( username = post.get('username',''), \
													password = post.get('passwd',''), \
													email = post.get('email',''), \
													)
				newuser.save()
				new_myuser = MyUser(user = newuser, \
									name = post.get('name',''), \
									num = post.get('num',''), \
									classnum = post.get('classnum',''), \
									permission = 1, \
									headImg = get_headimg(post.get('num',''))
									)
				new_myuser.save()
				status = 'success'
	content = {'active_menu':'homepage','status':status,'num_need_check':num_need_check(),'user':''}
	return render_to_response('signup.html', content, context_instance = RequestContext(req))

def login(req):
	if req.session.get('username',''):
		return HttpResponseRedirect('/')
	status = ''
	if req.POST:
		post = req.POST
		username = post.get('username','')
		password = post.get('passwd','')
		user = auth.authenticate(username = username, password = password)
		if user is not None:
			if user.is_active:
				auth.login(req,user)
				req.session['username'] = username
				return HttpResponseRedirect('/')
			else:
				status = 'not_active'
		else:
			status = 'not_exist_or_passwd_err'
	content = {'active_menu':'homepage','status':status,'num_need_check':num_need_check(),'user':''}
	return render_to_response('login.html', content, context_instance = RequestContext(req))

def logout(req):
	auth.logout(req)
	return HttpResponseRedirect('/')

def submit_report(req):
	username = req.session.get('username','')
	content = {'active_menu':'submitReport','num_need_check':num_need_check()}
	status = ''
	if username != '':
		user = MyUser.objects.get(user__username = username)
		content['user'] = user
	else:
		return HttpResponseRedirect('/login/')
	if req.POST:
		post = req.POST
		if req.FILES:
			img1 = req.FILES['img1']
			img2 = req.FILES['img2']
			bucket = Bucket('img')
			bucket.put()
			bucket.post(acl='.r:.sinaapp.com,.r:sae.sina.com.cn')
			tut1 = img1._name.split('.')[-1]
			tut2 = img2._name.split('.')[-1]
			if tut1.lower() not in ['jpg','jpeg','bmp','gif','png']:
				tut1 = 'jpg'
			if tut2.lower() not in ['jpg','jpeg','bmp','gif','png']:
				tut2 = 'jpg'
			dt_str = datetime.datetime.strftime(datetime.datetime.now(),'%Y%m%d%H%M%S')
			filename1 = dt_str + str(randint(100,999)) + '.' + tut1
			filename2 = dt_str + str(randint(100,999)) + '.' + tut2
			bucket.put_object(filename1,img1)
			bucket.put_object(filename2,img2)
		info = post.get('info','')
		if len(info) < 500:
			status = 'info_short'
		else:
			report = Report(
							name = post.get('name',''),
							start_time = post.get('start_time',''),
							end_time = post.get('end_time',''),
							address = post.get('address',''),
							status = 1,
							apply_time = 0,
							apply_score = 0,
							report_type = post.get('report_type',''),
							author_type = post.get('author_type',''),
							info_type = post.get('info_type',''),
							author = user,
							img1 = bucket.generate_url(filename1), \
							img2 = bucket.generate_url(filename2), \
							)
			if post.get('info_type','') == '2':
				a = re.compile(r'(<script)(.*)(>)',re.I)
				res = r'&lt;script\2&gt;'
				report.info = a.sub(res,info)
			else:
				report.info = info
			report.save()
			status = 'success'
		content['status'] = status
	return render_to_response('submitreport.html', content, context_instance = RequestContext(req))

def report_list(req):
	username = req.session.get('username','')
	if username != '':
		user = MyUser.objects.get(user__username = username)
	else:
		return HttpResponseRedirect('/login/')
	report_list = Report.objects.filter(author = user).order_by('-submit_time')
	# TODO: Add some info about report list and score
	content = {'active_menu':'checkReport','num_need_check':num_need_check(),'user':user,'report_list':report_list}
	return render_to_response('report_list.html',content)

def report_edit(req):
	username = req.session.get('username','')
	status = ''
	if username != '':
		user = MyUser.objects.get(user__username = username)
	else:
		return HttpResponseRedirect('/login/')
	Id = req.GET.get('id','')
	try:
		report = Report.objects.get(pk = Id)
	except:
		return HttpResponseRedirect('/reportlist/')
	if report.author != user:
		return HttpResponseRedirect('/reportlist/')
	else:
		if report.status != 1:
			status = 'cannot_edit'
		else:
			if req.POST:
				post = req.POST
				if req.FILES:
					img1 = req.FILES['img1']
					img2 = req.FILES['img2']
					bucket = Bucket('img')
					bucket.put()
					bucket.post(acl='.r:.sinaapp.com,.r:sae.sina.com.cn')
					tut1 = img1._name.split('.')[-1]
					tut2 = img2._name.split('.')[-1]
					if tut1.lower() not in ['jpg','jpeg','bmp','gif','png']:
						tut1 = 'jpg'
					if tut2.lower() not in ['jpg','jpeg','bmp','gif','png']:
						tut2 = 'jpg'
					dt_str = datetime.datetime.strftime(datetime.datetime.now(),'%Y%m%d%H%M%S')
					filename1 = dt_str + str(randint(100,999)) + '.' + tut1
					filename2 = dt_str + str(randint(100,999)) + '.' + tut2
					bucket.put_object(filename1,img1)
					bucket.put_object(filename2,img2)
				info = post.get('info','')
				if len(info) < 500:
					status = 'info_short'
				else:
					report.name = post.get('name','')
					report.start_time = post.get('start_time','')
					report.end_time = post.get('end_time','')
					report.address = post.get('address','')
					report.report_type = post.get('report_type','')
					report.author_type = post.get('author_type','')
					report.info_type = post.get('info_type','')
					try:
						img1 = bucket.generate_url(filename1)
						img2 = bucket.generate_url(filename2)
						report.img1 = img1
						report.img2 = img2
					except:
						pass
					if post.get('info_type','') == '2':
						a = re.compile(r'(<script)(.*)(>)',re.I)
						res = r'&lt;script\2&gt;'
						report.info = a.sub(res,info)
					else:
						report.info = info
					report.save()
					status = 'success'
	content = {'user':user,'active_menu':'submitReport','num_need_check':num_need_check(),'report':report, 'status':status}
	return render_to_response("report_edit.html",content,context_instance = RequestContext(req))

def report_detail(req):
	username = req.session.get('username','')
	if username != '':
		user = MyUser.objects.get(user__username = username)
	else:
		return HttpResponseRedirect('/login/')
	Id = req.GET.get('id','')
	try:
		report = Report.objects.get(pk = Id)
	except:
		if user.permission == 1:
			return HttpResponseRedirect('/reportlist/')
		elif user.permission > 1 and num_need_check() > 0:
			return HttpResponseRedirect('/auditinglist/')
		else:
			return HttpResponseRedirect('/')
	if user.permission == 1:
		if report.author != user:
			return HttpResponseRedirect('/reportlist/')
	if report.info_type == 2:
		report.info = markdown(report.info)
	content = {'report':report,'user':user,'num_need_check':num_need_check(),'active_menu':'checkReport'}
	return render_to_response('report.html',content)

def auditing_list(req):
	username = req.session.get('username','')
	if username != '':
		user = MyUser.objects.get(user__username = username)
	else:
		return HttpResponseRedirect('/login/')
	if user.permission == 1:
		return HttpResponseRedirect('/')
	else:
		auditing_list = Report.objects.filter(status = 1)
	content = {'auditing_list':auditing_list,'user':user,'num_need_check':num_need_check(),'active_menu':'auditingReport'}
	return render_to_response('auditing_list.html',content)

def report_auditing(req):
	username = req.session.get('username','')
	if username != '':
		user = MyUser.objects.get(user__username = username)
	else:
		return HttpResponseRedirect('/login/')
	if user.permission == 1:
		return HttpResponseRedirect('/')
	else:
		Id = req.GET.get('id','')
		try:
			report = Report.objects.get(pk = Id)
		except:
			if user.permission > 1 and num_need_check() > 0:
				return HttpResponseRedirect('/auditinglist/')
			else:
				return HttpResponseRedirect('/')
	if req.POST:
		post = req.POST
		status = post.get('status',1)
		report.status = status
		if status == '2':
			report.apply_score = post.get('apply_score',0)
			report.apply_time = post.get('apply_time',0)
		report.checker = user.name
		report.save()
		url = '/reportlist/detail/?id=' + str(report.id)
		return HttpResponseRedirect(url)
	if report.info_type == 2:
		report.info = markdown(report.info)
	content = {'user':user,'num_need_check':num_need_check(),'active_menu':'auditingReport','report':report}

volunteer/templates/auditing_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}审核列表{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h2 class="text-center">待审核报告列表</h2>
			{% for item in auditing_list %}
				<div class="list-group-item">
					<a href="/reportlist/auditing/?id={{ item.id }}" class="list-group-item">
						<h4 class="list-group-item-heading">{{ item.name }}</h4>
						<p class="list-group-item-text">{{ item.submit_time|date:"Y-m-d H:i:s" }}</p>
						<p class="list-group-item-text text-info">{{ item.author }}</p>
					</a>
				</div>
			{% empty %}
				<a href="/querry/" class="list-group-item active">
					<h4 class="list-group-item-heading">暂无未审核报告。</h4>
					<p class="list-group-item-text">点击查看统计。</p>
				</a>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

volunteer/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}登陆{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'not_active' %}
				<div class="well">
					<h2 class="text-danger text-center">用户已被封禁</h2>
				</div>
			{% elif status == 'not_exist_or_passwd_err' %}
				<div class="well">
					<h2 class="text-danger text-center">用户不存在或密码错误</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">请登陆</h1>

				<div class="form-group">
					<label for="id_user_name" class="col-md-3 control-label">用户名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_user_name" required name="username" autofocus>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_passwd" class="col-md-3 control-label">密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="passwd" id="id_passwd">
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">登陆</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

volunteer/templates/report_auditing.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}报告审核{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12"><h1 class="text-center">{{ report.name }}</h1></div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
			{% if report.status == 1 %}
				<h2 class="text-center text-info">待审核</h2>
			{% elif report.status == 2 %}
				<h2 class="text-center text-success">审核通过，已认定{{report.apply_time}}小时，每小时{{report.apply_score}}}分</h2>
			{% else %}
				<h2 class="text-center text-danger">审核未通过</h2>
			{% endif %}
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-7">
			<div class="col-md-12">
				<h3>姓名：{{ report.author.name }}</h3>
			</div>
			<div class="col-md-12">
				<h3>学号：{{ report.author.num }}</h3>
			</div>
			<div class="col-md-12">
				<h3>活动开始时间：{{ report.start_time|date:"Y-m-d H:i" }}</h3>
			</div>
			<div class="col-md-12">
				<h3>活动结束时间：{{ report.end_time|date:"Y-m-d H:i" }}</h3>
			</div>
			<div class="col-md-12">
				<h3>活动地点：{{ report.address }}</h3>
			</div>
			<div class="col-md-12">
				<h3>活动类型：
					{% if report.report_type == 1 %}
						专业类
					{% elif report.report_type == 2 %}
						非专业类
					{% else %}
						实践类
					{% endif %}
				</h3>
			</div>
			<div class="col-md-12">
				<h3>参加身份：
					{% if report.author_type == 1 %}
						组织者
					{% else %}
						参与者
					{% endif %}
				</h3>
			</div>
		</div>
		<div class="col-md-5">
			<img src="{{ report.author.headImg }}" class="img-rounded">
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
			{% if report.info_type == 1 %}
				<pre>{{ report.info }}</pre>
			{% elif report.info_type == 2 %}
				{{ report.info|safe }}
			{% endif %}
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-6">
			<img src="{{ report.img1 }}" class="img-rounded img-responsive">
		</div>
		<div class="col-md-6">
			<img src="{{ report.img2 }}" class="img-rounded img-responsive">
		</div>
	</div>
	<hr>
	<div class="row">
		<form method="post">
		{% csrf_token %}
			<div class="form-group col-md-4">
				<label for="id_apply_time">认定时长（小时）</label>
				<input type="text" class="form-control" id="id_apply_time" name="apply_time" required>
			</div>
			<div class="form-group col-md-4">
				<label for="id_apply_score">认定分数（分/小时）</label>
				<input type="text" class="form-control" id="id_apply_score" name="apply_score" required>
			</div>
			<div class="form-group col-md-4">
				<label for="id_status">认定结果</label>
				<select class="form-control" id="id_status" name="status">
					<option value="2">通过</option>
					<option value="3">不通过</option>
				</select>
			</div>
			<div class="form-group col-md-4 col-md-offset-4">
				<button class="btn btn btn-primary btn-block" type="submit">提交</button>
			</div>
		</form>
	</div>
</div>

{% endblock %}

volunteer/templates/report_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}修改报告{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">报告修改成功</h2>
				</div>
			{% elif status == 'info_short' %}
				<div class="well">
					<h2 class="text-warning text-center">总结字数不足，请继续完善。</h2>
				</div>
			{% elif status == 'cannot_edit' %}
				<div class="well">
					<h2 class="text-danger text-center">报告已被审核，不能再次修改。</h2>
				</div>
			{% endif %}
			<form role="form" method="post" enctype="multipart/form-data">
				{% if status == 'cannot_edit' %}
					<fieldset disabled>
				{% endif %}
				{% csrf_token %}
				<div class="form-group col-md-12">
					<label for="id_reportname">志愿服务名称</label>
					<input type="text" class="form-control" id="id_reportname" name="name" required value="{{ report.name }}">
				</div>
				<div class="form-group col-md-6">
					<label for="id_starttime">服务开始时间(请点击选择日期，并输入具体时间点
)</label>
					<input type="datetime-local" class="form-control" id="id_starttime" name="start_time" required>
				</div>
				<div class="form-group col-md-6">
					<label for="id_endtime">服务结束时间(请点击选择日期，并输入具体时间点
)</label>
					<input type="datetime-local" class="form-control" id="id_endtime" name="end_time" required>
				</div>
				<div class="form-group col-md-12">
					<label for="id_address">志愿服务地点</label>
					<input type="text" class="form-control" id="id_address" name="address" required value="{{ report.address }}">
				</div>
				<div class="form-group col-md-4">
					<label for="id_reporttype">志愿服务类型</label>
					<select class="form-control" id="id_reporttype" name="report_type">
						<option value="1">专业类</option>
						<option value="2">非专业类</option>
						<option value="3">实践类</option>
					</select>
				</div>
				<div class="form-group col-md-4">
					<label for="id_authortype">参加身份</label>
					<select class="form-control" id="id_authortype" name="author_type">
						<option value="1">组织者</option>
						<option value="2">参与者</option>
					</select>
				</div>
				<div class="form-group col-md-4">
					<label for="id_infotype">报告格式</label>
					<select class="form-control" id="id_infotype" name="info_type">
						<option value="1">纯文本</option>
						<option value="2">MarkDown</option>
					</select>
				</div>
				<div class="form-group col-md-12">
					<label for="id_info">活动总结(内容需大于500字方能提交)</label>
					<textarea name="info" rows="15" warp="hard" cols="105" id="id_info">{{ report.info }}</textarea>
				</div>
				<div class="form-group col-md-6">
					<label for="img1">活动图片1</label>
					<input type="file" id="img1" name="img1">
					<p class="help-block">请上传能够认定活动真实性的照片。</p>
				</div>
				<div class="form-group col-md-6">
					<label for="img2">活动图片2</label>
					<input type="file" id="img2" name="img2">
					<p class="help-block">每张照片大小不超过2.5M。</p>
				</div>
				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit" id="id_submit">修改</button>
					</div>
				</div>
				{% if status == 'cannot_edit' %}
					</fieldset>
				{% endif %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

volunteer/templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}注册{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">注册成功！</h2>
				</div>
			{% elif status == 're_err' %}
				<div class="well">
					<h2 class="text-warning text-center">密码重复错误</h2>
				</div>
			{% elif status == 'user_exist' %}
				<div class="well">
					<h2 class="text-danger text-center">用户已经存在</h2>
				</div>
			{% elif status == 'num_exist' %}
				<div class="well">
					<h2 class="text-danger text-center">该学号已经注册</h2>
				</div>
			{% elif status == 'classnum_err' %}
				<div class="well">
					<h2 class="text-danger text-center">请用8位班号注册</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">请注册</h1>

				<div class="form-group">
					<label for="id_user_name" class="col-md-3 control-label">用户名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_user_name" required name="username" autofocus>
						<span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_passwd" class="col-md-3 control-label">密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="passwd" id="id_passwd">
					</div>
				</div>

				<div class="form-group">
					<label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="repasswd" id="id_repasswd">
					</div>	
				</div>
				
				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">姓名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="name" id="id_name">
					</div>
				</div>
				
				<div class="form-group">
					<label for="id_num" class="col-md-3 control-label">学号：</label>
					<div class="col-md-9">
						<input type="tel" class="form-control" required name="num" id="id_num">
					</div>
				</div>

				<div class="form-group">
					<label for="id_classnum" class="col-md-3 control-label">班号：</label>
					<div class="col-md-9">
						<input type="tel" class="form-control" required name="classnum" id="id_classnum">
						<span class="help-block">填写8位行政班班号，如：11303102</span>
					</div>
				</div>

				<div class="form-group">
					<label for="id_email" class="col-md-3 control-label">电子邮件：</label>
					<div class="col-md-9">
						<input type="email" class="form-control" required name="email" id="id_email">
					</div>	
				</div>

				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">注册</button>
					</div>
				</div>

			</form>
		</div>
	</div>
</div>

{% endblock %}

volunteer/templates/submitreport.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}提交报告{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">报告提交成功</h2>
				</div>
			{% elif status == 'info_short' %}
				<div class="well">
					<h2 class="text-warning text-center">总结字数不足，请继续完善。</h2>
				</div>
			{% endif %}
			<form role="form" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-group col-md-12">
					<label for="id_reportname">志愿服务名称</label>
					<input type="text" class="form-control" id="id_reportname" name="name" required>
				</div>
				<div class="form-group col-md-6">
					<label for="id_starttime">服务开始时间(请点击选择日期，并输入具体时间点
)</label>
					<input type="datetime-local" class="form-control" id="id_starttime" name="start_time" required>
				</div>
				<div class="form-group col-md-6">
					<label for="id_endtime">服务结束时间(请点击选择日期，并输入具体时间点
)</label>
					<input type="datetime-local" class="form-control" id="id_endtime" name="end_time" required>
				</div>
				<div class="form-group col-md-12">
					<label for="id_address">志愿服务地点</label>
					<input type="text" class="form-control" id="id_address" name="address" required>
				</div>
				<div class="form-group col-md-4">
					<label for="id_reporttype">志愿服务类型</label>
					<select class="form-control" id="id_reporttype" name="report_type">
						<option value="1">专业类</option>
						<option value="2">非专业类</option>
						<option value="3">实践类</option>
					</select>
				</div>
				<div class="form-group col-md-4">
					<label for="id_authortype">参加身份</label>
					<select class="form-control" id="id_authortype" name="author_type">
						<option value="1">组织者</option>
						<option value="2">参与者</option>
					</select>
				</div>
				<div class="form-group col-md-4">
					<label for="id_infotype">报告格式</label>
					<select class="form-control" id="id_infotype" name="info_type">
						<option value="1">纯文本</option>
						<option value="2">MarkDown</option>
					</select>
				</div>
				<div class="form-group col-md-12">
					<label for="id_info">活动总结(内容需大于500字方能提交)</label>
				</div>
				<div class="form-group col-md-12">
					<textarea name="info" rows="15" warp="hard" id="id_info" style="width:100%"></textarea>
				</div>
				<div class="form-group col-md-6">
					<label for="img1">活动图片1</label>
					<input type="file" id="img1" name="img1" required>
					<p class="help-block">请上传能够认定活动真实性的照片。</p>
				</div>
				<div class="form-group col-md-6">
					<label for="img2">活动图片2</label>
					<input type="file" id="img2" name="img2" required>
					<p class="help-block">每张照片大小不超过2.5M。</p>
				</div>
				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit" id="id_submit">提交</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}